apiVersion: v2
name: io-pagopa-payment-updater-ms
description: io-pagopa-payment-updater-ms
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: microservice-chart
    version: 1.20.2
    repository: 'https://pagopa.github.io/aks-microservice-chart-blueprint'
